[package]
name = "rust-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
solana-sdk = "2.3.1"
serde = { version = "1.0", features = ["derive"] }
bs58 = "0.5"
base64 = "0.22"
bincode = "1.3"
solana-system-program = "1.18"