[package]
name = "rust-server"
version = "0.1.0"
edition = "2021"

[dependencies]
spl-token = "4.0.0"
base64 = "0.21"
tiny_http = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

bs58 = "0.5"
solana-client = "2.3.2"
solana-program = "2.3.0"
solana-sdk = "2.3.1"

